title: Chris Buckley
description: Chris Buckley's personal Web site
host: 0.0.0.0

url: https://cmbuckley.uk
baseurl: ""
paginate_path: "blog/page/:num/"
permalink: blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
paginate: 10

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - TODO

plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap

sass:
  style: compressed

defaults:
  - scope:
      type: pages
    values:
      og_type: website
  - scope:
      type: blog_categories
    values:
      layout: category

collections:
  blog_categories:
    output: true
    permalink: /blog/category/:name/

navigation:
 - title: Home
   url: /
 - title: CV
   url: /cv/
 - title: Contact
   url: /contact/
 - title: Blog
   url: /blog/
 - title: Interests
   url: /interests/
 - title: Projects
   url: /projects/

details:
   location: Meanwood
   company: Sky Betting & Gaming
   role: Solutions Architect

social:
   github:    cmbuckley
   linkedin:  cmbuckley
   email:     chris@cmbuckley.co.uk
   twitter:   _cmbuckley
   facebook:  cmbuckley
   instagram: c.m.buckley
   amazon:    https://bux.re/amzn
   google:    https://bux.re/+
