title: Chris Buckley’s Personal Web Site
description: Chris Buckley's Personal Web Site
host: 0.0.0.0

url: https://cmbuckley.co.uk
baseurl: ""
paginate_path: "blog/page/:num/"
permalink: blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /
 - title: CV
   url: /cv/
 - title: Projects
   url: /projects/

social:
   github:    cmbuckley
   linkedin:  cmbuckley
   email:     chris@cmbuckley.co.uk
   twitter:   _cmbuckley
   facebook:  cmbuckley
   instagram: c.m.buckley
   amazon:    https://bux.re/amzn
   google:    https://bux.re/+
