title: Chris Buckley
description: The personal Web site of Chris Buckley, a Leeds-born software enthusiast and live music fan.
host: 0.0.0.0

url: https://cmbuckley.co.uk
baseurl: ""
shorturl: https://bux.re
paginate_path: "blog/page/:num/"
permalink: blog/:year/:month/:day/:title/
repository: cmbuckley/cmbuckley.github.io

timezone: Europe/London
locale: en-GB

markdown: kramdown
highlighter: rouge
paginate: 10

exclude:
  - CNAME
  - Gemfile
  - LICENSE
  - README.md
  - TODO
  - staticman.yml
  - vendor

plugins:
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-redirect-from

sass:
  style: compressed

defaults:
  - scope:
      type: pages
    values:
      og_type: website
  - scope:
      type: blog_categories
    values:
      layout: category

collections:
  blog_categories:
    output: true
    permalink: /blog/category/:name/

details:
   location: Meanwood
   company: Sky Betting & Gaming
   role: Solutions Architect
