[context.branch-deploy]
command = "printf \"url: %s\" \"$DEPLOY_PRIME_URL\" > _preview.yml; jekyll build --config _config.yml,_preview.yml && rspec"

  [[context.branch-deploy.plugins]]
  package = "netlify-plugin-seo-lint"

    [context.branch-deploy.plugins.inputs]
    internalLinksTrailingSlash = false

[context.deploy-preview]
command = "printf \"url: %s\" \"https://staging-$REVIEW_ID.cmbuckley.co.uk\" > _preview.yml; jekyll build --config _config.yml,_preview.yml && rspec"

  [[context.deploy-preview.plugins]]
  package = "netlify-plugin-seo-lint"

    [context.deploy-preview.plugins.inputs]
    host = "https://staging-$REVIEW_ID.cmbuckley.co.uk"
    hostExpansion = true
    internalLinksTrailingSlash = false

[[context.production.plugins]]
package = "netlify-plugin-seo-lint"

  [context.production.plugins.inputs]
  internalLinksTrailingSlash = false

[build]
command = "jekyll build --config _config.yml,_staging.yml && rspec"

  [build.environment]
  RUBY_VERSION = "3.3.9"

[[plugins]]
package = "netlify-plugin-html-validate"

  [plugins.inputs]
  ext = "html"
  config = ".htmlvalidate.json"

[[headers]]
for = "/*"

  [headers.values]
  X-Robots-Tag = "noindex, nofollow"
