name: Update Cloudflare Worker
on:
  push:
    branches: main
    paths:
      - '_cf/**'
jobs:
  cloudflare-worker:
    name: Deploy Cloudflare Worker
    runs-on: ubuntu-latest
    strategy:
      matrix:
        worker: [security-headers, netlify-deployment-status]
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Cloudflare Worker (${{ matrix.worker }})
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          workingDirectory: _cf/${{ matrix.worker }}
