name: Update Cloudflare Workers
on:
  push:
    branches: main
    paths:
      - '_cf/**'
jobs:
  cloudflare-worker:
    name: Deploy Cloudflare Workers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy security-headers Cloudflare Worker
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: _cf/security-headers
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
