name: Rebuild GitHub Pages sites
on:
  workflow_dispatch:
  schedule:
    - cron: '15 0 1 JAN *'
jobs:
  rebuild-pages:
    name: Rebuild GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Trigger builds on matching repos
        env:
          GH_USER: ${{ github.repository_owner }}
          GH_TOKEN: ${{ secrets.GH_TOKEN_REBUILD }}
        run: |
          gh api users/$GH_USER/repos -X GET -f type=public --paginate -q \
          '.[] | select(.has_pages == true and .fork == false and (any(.topics[]; contains("noindex")) | not)) | .url' \
            | while read repo; do
              echo "$repo:"
              gh api $repo/pages/builds -X POST
            done
